services:
  flask:
    build: ./backend
    container_name: flask_server
    ports:
      - '8000:8000'

  nginx:
    build: ./frontend
    container_name: nginx_server
    ports:
      - '9000:80'
    depends_on:
      - flask
