openapi: 3.0.3
info:
  title: User API
  description: A simple API for managing users.
  version: 1.0.0
servers:
  - url: http://localhost:9000
    description: Local development server
paths:
  /greets:
    get:
      summary: Return a greeting message
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Internal server error
    post:
      summary: Create a new user
      description: Creates a new user with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: User created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: integer
          format: int64
          description: The unique ID of the user.
          example: 123
        name:
          type: string
          description: The name of the user.
          example: John Doe
        email:
          type: string
          format: email
          description: The email address of the user.
          example: john.doe@example.com
    NewUser:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
          description: The name of the new user.
          example: Jane Smith
        email:
          type: string
          format: email
          description: The email address of the new user.
          example: jane.smith@example.com
