openapi: 3.0.3
info:
  title: User API
  description: A simple API for managing users.
  version: 1.0.0
servers:
  - url: http://localhost:9000
    description: Local development server
paths:
  /greets:
    get:
      summary: Return a greeting message
      responses:
        '200':
          description: A greeting message.
          content:
            application/json:
              schema:
                type: string
                example: 'Hello, World!'
  /calculate:
    post:
      summary: Perform a calculation
      requestBody:
        description: Input numbers for the calculation.
        required: true
        content:
          application/json:
            type: object
              properties:
              num1:
                type: number
                example: 5
              num2:
                type: number
                example: 10
      responses:
        '201':
          description: User created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
        '500':
          description: Internal server error


